### PR TITLE
Added class_names; Allow StateMachinePlayer to be inherited; Improved feedbacks;

### LINKED ISSUE #83: StateMachinePlayer doesn't have a class_name, disallowing static typing
I like having static typing. Less error prone.

In godot, it also make autocomplete work deeper than 1 level.

With variant:

image

image

With static typing:

image

Static typing aside, I also would like to do as many thing from code as possible in general, without relying on the node tree / node tab. Having a class name would help with that.

### PR DESCRIPTION
**Pull request by murilosr**
* Adds class_name to StateMachinePlayer and StackPlayer (Fix #83)
* Fixes a bug in RemoteDebugger when StateMachinePlayer is inherited by other class
* Adds class_name to StackPlayer to be possible to add icon on Create New Node window
* Improves feedback to user with Warning on Node Tree (Editor) and assertions (code)

Tested with Godot 4.2 and 4.3, even with a large project (my own game) that uses a lot of StateMachinePlayers and StateMachines (17 until now).

### CODE REVIEW

**Comment by murilosr** [comment]
**Warnings are displayed at Scene Tree if the user doesn't set a StateMachine or have a State Machine without an Entry node**
Screenshot from 2024-10-12 12-48-17

Screenshot from 2024-10-12 12-47-47

---

**Assertion will fail with a proper error code if the Scene is run with a StateMachinePlayer without a State Machine or without an Entry node**

Screenshot from 2024-10-12 12-48-28

**Comment by imjp94** [comment]
Well done!

Just some minor fix before merge:
- Remove comma from the warning messages in `_get_configuration_warnings()`. I tested it myself, it can display properly without the comma
- Reword `Property "state_machine" is required` and `A 'state_machine' is needed to run` to something like `StateMachine resource is required`, to emphasize a `Resource` is missing. Feel free to use your own word.
Screenshot 2024-10-13 164234
_CollisionShape3D warning as an example_

**Comment by murilosr** [comment]
Done.

---
New messages:

**Node warnings:**
* The StateMachine provided does not have an Entry node.\nPlease create one to it works properly.
* StateMachinePlayer needs a StateMachine to run.\nPlease create a StateMachine resource to it.

**Assertions:**
* A StateMachine resource is required to start this StateMachinePlayer.
* The StateMachine provided does not have an Entry node.

**Comment by imjp94** [comment]
Thanks!

**Comment by ianmckenna87** [comment]
Brilliant guys, glad to see this add on is still alive and kicking! It's hands down the most intuitive state machine plug-in for Godot!

**Pull request merged**
